/*
 * Copyright (C) 2026 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#if 0
// The preprocessor evaluates `#if 0` to false, so this block is excluded
// from the preprocessed output that gets embedded into JSCBuiltins.cpp.
// We wrap the developer documentation this way because comments survive
// under `-CC` and we do not want to inline this text at the top of every
// preprocessed builtin. The rules:
//
//   1. Self-contained. No `#include` of other headers. Anything a CPP would
//      emit while expanding an `#include` lands at the top of every
//      preprocessed builtin .js, bloating JSCBuiltins.cpp. Use
//      `-imacros <header>` from the build system if you only need another
//      header's macros; the build already passes `-imacros wtf/Platform.h`
//      so `ENABLE(X)` / `USE(X)` / `HAVE(X)` work in builtins.
//
//   2. Every macro MUST use the `JSC_BUILTIN_` prefix. Builtin .js files use
//      @-prefixed intrinsic identifiers (@toObject, @isCallable,
//      @MAX_SAFE_INTEGER, ...) resolved by the bytecode compiler. A macro
//      whose name collides with an intrinsic would silently replace it and
//      corrupt generated bytecode.
//
//   3. Only `#define` directives belong here. Directives produce no output.
//
//   4. The build invokes the preprocessor with
//      `-DWTF_PREPROCESSING_FOR_TEXT_REPLACEMENT_ONLY=1`, which signals to
//      `wtf/Platform.h` (injected via `-imacros`) that emission-only
//      constructs like `#pragma strict_gs_check(on)` must be suppressed.
//      Any new emission-only construct in Platform.h must be guarded the
//      same way so it does not leak into preprocessed builtin output.
#endif

#define JSC_BUILTIN_INLINE @alwaysInline
#define JSC_BUILTIN_LINK_TIME_CONSTANT @linkTimeConstant
#define JSC_BUILTIN_VISIBILITY_PRIVATE @visibility=Private
#define JSC_BUILTIN_VISIBILITY_PRIVATE_RECURSIVE @visibility=PrivateRecursive
#define JSC_BUILTIN_VISIBILITY_PUBLIC @visibility=Public
