// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include <array>
#include <wtf/HashFunctions.h>
#include <wtf/HashTraits.h>

namespace WebCore {

class Settings;

enum CSSPropertyID : uint16_t {
    CSSPropertyInvalid = 0,
    CSSPropertyCustom = 1,
    CSSPropertyTestTopPriority = 2,
    CSSPropertyTestHighPriority = 3,
    CSSPropertyFirstTestDescriptorForFirstDescriptor = 4,
    CSSPropertyFirstTestDescriptorForSecondDescriptor = 5,
    CSSPropertyTestAnimationWrapper = 6,
    CSSPropertyTestAnimationWrapperAccelerationAlways = 7,
    CSSPropertyTestAnimationWrapperAccelerationThreadedOnly = 8,
    CSSPropertyTestBoundedRepetitionWithCommas = 9,
    CSSPropertyTestBoundedRepetitionWithCommasFixed = 10,
    CSSPropertyTestBoundedRepetitionWithCommasNoSingleItemOpt = 11,
    CSSPropertyTestBoundedRepetitionWithCommasSingleItemOpt = 12,
    CSSPropertyTestBoundedRepetitionWithSpaces = 13,
    CSSPropertyTestBoundedRepetitionWithSpacesFixed = 14,
    CSSPropertyTestBoundedRepetitionWithSpacesNoSingleItemOpt = 15,
    CSSPropertyTestBoundedRepetitionWithSpacesSingleItemOpt = 16,
    CSSPropertyTestBoundedRepetitionWithSpacesWithType = 17,
    CSSPropertyTestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious = 18,
    CSSPropertyTestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo = 19,
    CSSPropertyTestFunctionBoundedParameters = 20,
    CSSPropertyTestFunctionFixedParameters = 21,
    CSSPropertyTestFunctionNoParameters = 22,
    CSSPropertyTestFunctionParametersMatchAllAnyOrder = 23,
    CSSPropertyTestFunctionParametersMatchAllAnyOrderWithOptional = 24,
    CSSPropertyTestFunctionParametersMatchAllOrdered = 25,
    CSSPropertyTestFunctionParametersMatchAllOrderedWithOptional = 26,
    CSSPropertyTestFunctionParametersMatchOneOrMoreAnyOrder = 27,
    CSSPropertyTestFunctionSingleParameter = 28,
    CSSPropertyTestFunctionSingleParameterMatchOne = 29,
    CSSPropertyTestFunctionSingleParameterOptional = 30,
    CSSPropertyTestFunctionUnboundedParametersNoMin = 31,
    CSSPropertyTestFunctionUnboundedParametersWithMinimum = 32,
    CSSPropertyTestMatchAllAnyOrder = 33,
    CSSPropertyTestMatchAllAnyOrderWithOptional = 34,
    CSSPropertyTestMatchAllAnyOrderWithOptionalNoSingleItemOpt = 35,
    CSSPropertyTestMatchAllAnyOrderWithOptionalSingleItemOpt = 36,
    CSSPropertyTestMatchAllAnyOrderWithOptionalWithPreserveOrder = 37,
    CSSPropertyTestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt = 38,
    CSSPropertyTestMatchAllAnyOrderWithPreserveOrder = 39,
    CSSPropertyTestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt = 40,
    CSSPropertyTestMatchAllOrdered = 41,
    CSSPropertyTestMatchAllOrderedWithOptional = 42,
    CSSPropertyTestMatchAllOrderedWithOptionalNoSingleItemOpt = 43,
    CSSPropertyTestMatchAllOrderedWithOptionalSingleItemOpt = 44,
    CSSPropertyTestMatchOneOrMoreAnyOrder = 45,
    CSSPropertyTestMatchOneOrMoreAnyOrderNoSingleItemOpt = 46,
    CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrder = 47,
    CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt = 48,
    CSSPropertyTestNumericValueRange = 49,
    CSSPropertyTestProperty = 50,
    CSSPropertyTestSettingsOne = 51,
    CSSPropertyTestUnboundedRepetitionWithCommasWithMin = 52,
    CSSPropertyTestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt = 53,
    CSSPropertyTestUnboundedRepetitionWithCommasWithMinSingleItemOpt = 54,
    CSSPropertyTestUnboundedRepetitionWithSpacesNoMin = 55,
    CSSPropertyTestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt = 56,
    CSSPropertyTestUnboundedRepetitionWithSpacesWithMin = 57,
    CSSPropertyTestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt = 58,
    CSSPropertyTestUnboundedRepetitionWithSpacesWithMinSingleItemOpt = 59,
    CSSPropertyTestUsingSharedRule = 60,
    CSSPropertyTestUsingSharedRuleExported = 61,
    CSSPropertyTestUsingSharedRuleWithOverrideFunction = 62,
    CSSPropertyTestSinkPriority = 63,
    CSSPropertyTestLogicalPropertyGroupLogicalBlock = 64,
    CSSPropertyTestLogicalPropertyGroupLogicalInline = 65,
    CSSPropertyTestLogicalPropertyGroupPhysicalHorizontal = 66,
    CSSPropertyTestLogicalPropertyGroupPhysicalVertical = 67,
    CSSPropertyFont = 68,
    CSSPropertyTestShorthandOne = 69,
    CSSPropertyTestShorthandTwo = 70,
};

// Enum value of the first "real" CSS property, which excludes
// CSSPropertyInvalid and CSSPropertyCustom.
constexpr uint16_t firstCSSProperty = 2;
// Total number of enum values in the CSSPropertyID enum. If making an array
// that can be indexed into using the enum value, use this as the size.
constexpr uint16_t cssPropertyIDEnumValueCount = 71;
// Number of "real" CSS properties. This differs from cssPropertyIDEnumValueCount,
// as this doesn't consider CSSPropertyInvalid and CSSPropertyCustom.
constexpr uint16_t numCSSProperties = 69;
constexpr unsigned maxCSSPropertyNameLength = 77;
constexpr auto firstTopPriorityProperty = CSSPropertyID::CSSPropertyTestTopPriority;
constexpr auto lastTopPriorityProperty = CSSPropertyID::CSSPropertyTestTopPriority;
constexpr auto firstHighPriorityProperty = CSSPropertyID::CSSPropertyTestHighPriority;
constexpr auto lastHighPriorityProperty = CSSPropertyID::CSSPropertyTestHighPriority;
constexpr auto firstLowPriorityProperty = CSSPropertyID::CSSPropertyFirstTestDescriptorForFirstDescriptor;
constexpr auto lastLowPriorityProperty = CSSPropertyID::CSSPropertyTestSinkPriority;
constexpr auto firstLogicalGroupProperty = CSSPropertyID::CSSPropertyTestLogicalPropertyGroupLogicalBlock;
constexpr auto lastLogicalGroupProperty = CSSPropertyID::CSSPropertyTestLogicalPropertyGroupPhysicalVertical;
constexpr auto firstShorthandProperty = CSSPropertyID::CSSPropertyFont;
constexpr auto lastShorthandProperty = CSSPropertyID::CSSPropertyTestShorthandTwo;
constexpr uint16_t numCSSPropertyLonghands = firstShorthandProperty - firstCSSProperty;
extern const std::array<CSSPropertyID, 64> computedPropertyIDs;

struct CSSPropertySettings {
    WTF_MAKE_STRUCT_FAST_ALLOCATED;

    bool cssDescriptorEnabled : 1 { false };
    bool cssSettingsOneEnabled : 1 { false };

    CSSPropertySettings() = default;
    explicit CSSPropertySettings(const Settings&);
};

bool operator==(const CSSPropertySettings&, const CSSPropertySettings&);
void add(Hasher&, const CSSPropertySettings&);

constexpr bool isLonghand(CSSPropertyID);
bool isInternal(CSSPropertyID);
bool isExposed(CSSPropertyID, const Settings*);
bool isExposed(CSSPropertyID, const Settings&);
bool isExposed(CSSPropertyID, const CSSPropertySettings*);
bool isExposed(CSSPropertyID, const CSSPropertySettings&);

CSSPropertyID findCSSProperty(const char* characters, unsigned length);
ASCIILiteral nameLiteral(CSSPropertyID);
const AtomString& nameString(CSSPropertyID);
String nameForIDL(CSSPropertyID);

CSSPropertyID cascadeAliasProperty(CSSPropertyID);

template<CSSPropertyID first, CSSPropertyID last> struct CSSPropertiesRange {
    struct Iterator {
        uint16_t index { static_cast<uint16_t>(first) };
        constexpr CSSPropertyID operator*() const { return static_cast<CSSPropertyID>(index); }
        constexpr Iterator& operator++() { ++index; return *this; }
        constexpr bool operator==(std::nullptr_t) const { return index > static_cast<uint16_t>(last); }
    };
    static constexpr Iterator begin() { return { }; }
    static constexpr std::nullptr_t end() { return nullptr; }
    static constexpr uint16_t size() { return last - first + 1; }
};
using AllCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyID>(firstCSSProperty), lastShorthandProperty>;
using AllLonghandCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyID>(firstCSSProperty), lastLogicalGroupProperty>;
constexpr AllCSSPropertiesRange allCSSProperties() { return { }; }
constexpr AllLonghandCSSPropertiesRange allLonghandCSSProperties() { return { }; }

constexpr bool isLonghand(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= firstCSSProperty && static_cast<uint16_t>(property) < static_cast<uint16_t>(firstShorthandProperty);
}
constexpr bool isShorthand(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= static_cast<uint16_t>(firstShorthandProperty) && static_cast<uint16_t>(property) <= static_cast<uint16_t>(lastShorthandProperty);
}

WTF::TextStream& operator<<(WTF::TextStream&, CSSPropertyID);

} // namespace WebCore

namespace WTF {

template<> struct DefaultHash<WebCore::CSSPropertyID> : IntHash<unsigned> { };

template<> struct HashTraits<WebCore::CSSPropertyID> : GenericHashTraits<WebCore::CSSPropertyID> {
    static const bool emptyValueIsZero = true;
    static void constructDeletedValue(WebCore::CSSPropertyID& slot) { slot = static_cast<WebCore::CSSPropertyID>(std::numeric_limits<uint16_t>::max()); }
    static bool isDeletedValue(WebCore::CSSPropertyID value) { return static_cast<uint16_t>(value) == std::numeric_limits<uint16_t>::max(); }
};

} // namespace WTF

namespace std {

template<> struct iterator_traits<WebCore::AllCSSPropertiesRange::Iterator> { using value_type = WebCore::CSSPropertyID; };
template<> struct iterator_traits<WebCore::AllLonghandCSSPropertiesRange::Iterator> { using value_type = WebCore::CSSPropertyID; };

} // namespace std

