// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#include "config.h"
#include "StyleInterpolationWrapperMap.h"

#include "StylePropertyShorthand.h"

#define STYLE_INTERPOLATION_GENERATED_INCLUDE_TRAP 1
#include "StyleInterpolationWrappers.h"
#undef STYLE_INTERPOLATION_GENERATED_INCLUDE_TRAP
namespace WebCore {
namespace Style {
namespace Interpolation {

static WrapperBase* makeShorthandWrapper(CSSPropertyID id, const std::array<WrapperBase*, cssPropertyIDEnumValueCount>& wrappers)
{
    auto shorthand = shorthandForProperty(id);
    ASSERT(shorthand.length());

    auto longhandWrappers = WTF::compactMap(shorthand, [&](auto longhand) -> std::optional<WrapperBase*> {
        auto wrapper = wrappers[longhand];
        if (!wrapper)
            return std::nullopt;
        return wrapper;
    });

    return new ShorthandWrapper(id, WTFMove(longhandWrappers));
}

WrapperMap::WrapperMap()
    : m_wrappers {
        nullptr, // CSSPropertyID::CSSPropertyInvalid
        nullptr, // CSSPropertyID::CSSPropertyCustom
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestTopPriority, &RenderStyle::testTopPriority, &RenderStyle::setTestTopPriority), // CSSPropertyID::CSSPropertyTestTopPriority
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestHighPriority, &RenderStyle::testHighPriority, &RenderStyle::setTestHighPriority), // CSSPropertyID::CSSPropertyTestHighPriority
        nullptr, // CSSPropertyID::CSSPropertyFirstTestDescriptorForFirstDescriptor - not animatable (descriptor only)
        nullptr, // CSSPropertyID::CSSPropertyFirstTestDescriptorForSecondDescriptor - not animatable (descriptor only)
        new Wrapper<float>(CSSPropertyID::CSSPropertyTestAnimationWrapper, &RenderStyle::testAnimationWrapper, &RenderStyle::setTestAnimationWrapper), // CSSPropertyID::CSSPropertyTestAnimationWrapper
        new Wrapper<float>(CSSPropertyID::CSSPropertyTestAnimationWrapperAccelerationAlways, &RenderStyle::testAnimationWrapperAccelerationAlways, &RenderStyle::setTestAnimationWrapperAccelerationAlways), // CSSPropertyID::CSSPropertyTestAnimationWrapperAccelerationAlways
        new Wrapper<float>(CSSPropertyID::CSSPropertyTestAnimationWrapperAccelerationThreadedOnly, &RenderStyle::testAnimationWrapperAccelerationThreadedOnly, &RenderStyle::setTestAnimationWrapperAccelerationThreadedOnly), // CSSPropertyID::CSSPropertyTestAnimationWrapperAccelerationThreadedOnly
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestNumericValueRange, &RenderStyle::testNumericValueRange, &RenderStyle::setTestNumericValueRange), // CSSPropertyID::CSSPropertyTestNumericValueRange
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestProperty, &RenderStyle::testProperty, &RenderStyle::setTestProperty), // CSSPropertyID::CSSPropertyTestProperty
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestSettingsOne, &RenderStyle::testSettingsOne, &RenderStyle::setTestSettingsOne), // CSSPropertyID::CSSPropertyTestSettingsOne
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestUsingSharedRule, &RenderStyle::testUsingSharedRule, &RenderStyle::setTestUsingSharedRule), // CSSPropertyID::CSSPropertyTestUsingSharedRule
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestSinkPriority, &RenderStyle::testSinkPriority, &RenderStyle::setTestSinkPriority), // CSSPropertyID::CSSPropertyTestSinkPriority
        nullptr, // CSSPropertyID::CSSPropertyTestLogicalPropertyGroupLogicalBlock - logical, handled via resolution to physical
        nullptr, // CSSPropertyID::CSSPropertyTestLogicalPropertyGroupLogicalInline - logical, handled via resolution to physical
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestLogicalPropertyGroupPhysicalHorizontal, &RenderStyle::testLogicalPropertyGroupPhysicalHorizontal, &RenderStyle::setTestLogicalPropertyGroupPhysicalHorizontal), // CSSPropertyID::CSSPropertyTestLogicalPropertyGroupPhysicalHorizontal
        new DiscreteWrapper(CSSPropertyID::CSSPropertyTestLogicalPropertyGroupPhysicalVertical, &RenderStyle::testLogicalPropertyGroupPhysicalVertical, &RenderStyle::setTestLogicalPropertyGroupPhysicalVertical), // CSSPropertyID::CSSPropertyTestLogicalPropertyGroupPhysicalVertical
        nullptr, // CSSPropertyID::CSSPropertyFont - shorthand, will perform fix-up below
        nullptr, // CSSPropertyID::CSSPropertyTestShorthandOne - shorthand, will perform fix-up below
        nullptr, // CSSPropertyID::CSSPropertyTestShorthandTwo - shorthand, will perform fix-up below
    }
{
    // Build animatable shorthand wrappers from longhand wrappers initialized above.

    m_wrappers[CSSPropertyID::CSSPropertyFont] = makeShorthandWrapper(CSSPropertyID::CSSPropertyFont, m_wrappers);
    m_wrappers[CSSPropertyID::CSSPropertyTestShorthandOne] = makeShorthandWrapper(CSSPropertyID::CSSPropertyTestShorthandOne, m_wrappers);
    m_wrappers[CSSPropertyID::CSSPropertyTestShorthandTwo] = makeShorthandWrapper(CSSPropertyID::CSSPropertyTestShorthandTwo, m_wrappers);
}

} // namespace WebCore
} // namespace Style
} // namespace Interpolation

